# Generated by Django 5.2.6 on 2025-09-23 13:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_mep', models.CharField(max_length=32, unique=True, verbose_name='Carnet/ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('section', models.CharField(blank=True, default='', max_length=20, verbose_name='Sección')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('abandono', 'Abandono')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.CharField(blank=True, default='', max_length=80)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
