# Generated by Django 5.2.6 on 2025-10-10 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_action_created_at_alter_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='en_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action',
            name='escuela_origen',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Escuela de origen'),
        ),
        migrations.AddField(
            model_name='action',
            name='transferido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de residencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Indefinido', 'Indefinido')], default='Indefinido', max_length=15, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_id_1',
            field=models.CharField(default='Missing ID', max_length=50, verbose_name='Cédula encargado 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_id_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula encargado 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_id_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula encargado 3'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name_1',
            field=models.CharField(default='Missing Parent', max_length=120, verbose_name='Nombre encargado 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre encargado 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name_3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre encargado 3'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone_1',
            field=models.CharField(default='Missing PhoneNumber', max_length=30, verbose_name='Teléfono encargado 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono encargado 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone_3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono encargado 3'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Costa Rica', max_length=60, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('abandono', 'Abandono')], db_index=True, max_length=20),
        ),
    ]
