# Generated by Django 5.2.6 on 2025-10-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_action_en_revision_action_escuela_origen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='en_revision',
            new_name='on_revition',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='escuela_origen',
            new_name='origin_school',
        ),
    ]
