# Generated by Django 5.2.6 on 2025-10-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_en_revision_action_on_revition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='transferido',
            new_name='transfered',
        ),
    ]
