# Generated by Django 5.2.6 on 2025-10-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_transferido_action_transfered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='on_revition',
            new_name='on_revision',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='transfered',
            new_name='transferred',
        ),
    ]
