# Generated by Django 5.2.6 on 2025-10-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_on_revition_action_on_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_reference1',
            field=models.CharField(default='Missing PhoneNumber', max_length=30, verbose_name='Parentesco al estudiante 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_reference2',
            field=models.CharField(default='Missing PhoneNumber', max_length=30, verbose_name='Parentesco al estudiante 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_reference3',
            field=models.CharField(default='Missing PhoneNumber', max_length=30, verbose_name='Parentesco al estudiante 3'),
        ),
        migrations.AddField(
            model_name='student',
            name='institutional_guardian',
            field=models.CharField(default='Missing Parent', max_length=120, verbose_name='Nombre encargado 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='ongoing_age',
            field=models.TextField(max_length=2, null=True, verbose_name='Edad cumplida el presente año'),
        ),
        migrations.AddField(
            model_name='student',
            name='ongoing_age_year',
            field=models.TextField(max_length=4, null=True, verbose_name='Año de referencia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Dirección de residencia'),
        ),
    ]
