# Generated by Django 5.2.6 on 2025-10-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_birth_place_student_guardian_reference1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardian_reference1',
            new_name='guardian_relationship_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_reference2',
            new_name='guardian_relationship_2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_reference3',
            new_name='guardian_relationship_3',
        ),
    ]
