# Generated by Django 5.2.6 on 2025-10-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_guardian_reference1_student_guardian_relationship_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surnames', 'first_name']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='surnames',
        ),
    ]
