# Generated by Django 5.2.6 on 2025-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='last_edition_by',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='action',
            name='matriculate_level',
            field=models.CharField(choices=[('interactivo_ii', 'Interactivo_II'), ('transicion', 'Transicion'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('aula_integrada', 'Aula_Integrada')], db_index=True, default='primero', max_length=20, verbose_name='Nivel a Matricular'),
        ),
        migrations.AlterField(
            model_name='action',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
    ]
