# Generated by Django 5.2.6 on 2025-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_action_last_edition_by_action_matriculate_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.AlterField(
            model_name='action',
            name='matriculate_level',
            field=models.CharField(choices=[('interactivo_ii', 'Interactivo_II'), ('transicion', 'Transicion'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('aula_integrada', 'Aula_Integrada')], db_index=True, default='primero', max_length=20, verbose_name='Nivel a| Matricular'),
        ),
    ]
