# Generated by Django 5.2.6 on 2025-11-09 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_created_by_customuser_visitor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Administrador que creó este visitante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('DEV', 'Desarrollador'), ('ADMIN', 'Administrativo'), ('VISITOR', 'Visitante')], default='ADMIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visitor_code',
            field=models.CharField(blank=True, help_text='Código visible para el visitante (clave).', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visitor_expires_at',
            field=models.DateField(blank=True, help_text='Fecha de expiración de la clave.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visitor_suspended_at',
            field=models.DateTimeField(blank=True, help_text='Si se establece, el visitante está suspendido.', null=True),
        ),
    ]
