# Generated by Django 5.2.6 on 2025-11-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_created_by_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Indefinido', 'Indefinido')], default='Indefinido', max_length=15, verbose_name='Género'),
        ),
    ]
