# Generated by Django 5.2.6 on 2025-10-07 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('create', 'Creación'), ('update', 'Edición'), ('delete', 'Eliminación'), ('read', 'Consulta')], max_length=16)),
                ('entity', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido')], default='success', max_length=16)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
