# Generated by Django 5.2.6 on 2025-10-10 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=60)),
                ('entity', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(default='success', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_personallog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
